// VGFlow generated Playwright config — DO NOT edit; regenerated by /vg:test
// Headed when interactive, headless in CI. Trace + video + screenshot on failure.
import { defineConfig } from '@playwright/test';

const isCi = !!process.env.CI;
const headedFlag = process.env.VG_HEADED;  // 'true' / 'false' / undefined
const headed = headedFlag === 'true' ? true : headedFlag === 'false' ? false : !isCi;

export default defineConfig({
  testDir: '.',
  fullyParallel: false,
  workers: headed ? 1 : undefined,  // serial when headed for watchability
  timeout: 60_000,
  use: {
    headless: !headed,
    launchOptions: {
      slowMo: headed ? Number(process.env.VG_SLOW_MO ?? 250) : 0,
    },
    trace: 'retain-on-failure',
    video: 'retain-on-failure',
    screenshot: 'only-on-failure',
    baseURL: process.env.VG_BASE_URL,
  },
  reporter: isCi
    ? [['dot'], ['json', { outputFile: 'playwright-results.json' }]]
    : [['list'], ['html', { open: 'never' }]],
});
