// VGFlow generated Playwright config — DO NOT edit; regenerated by /vg:test
// Headed when interactive, headless in CI. Trace + video + screenshot on failure.
// H13 (v4.12.0): JSON reporter ALWAYS on so AI can inspect per-test failures
// (console, network, error stack) — required for AI introspection in addition to
// human-readable list/dot reporters. Without JSON, AI sees only PASS/FAIL counts.
import { defineConfig } from '@playwright/test';

const isCi = !!process.env.CI;
const headedFlag = process.env.VG_HEADED;  // 'true' / 'false' / undefined
const headed = headedFlag === 'true' ? true : headedFlag === 'false' ? false : !isCi;

export default defineConfig({
  testDir: '.',
  fullyParallel: false,
  workers: headed ? 1 : undefined,  // serial when headed for watchability
  timeout: 60_000,
  use: {
    headless: !headed,
    launchOptions: {
      slowMo: headed ? Number(process.env.VG_SLOW_MO ?? 250) : 0,
    },
    trace: 'retain-on-failure',
    video: 'retain-on-failure',
    screenshot: 'only-on-failure',
    baseURL: process.env.VG_BASE_URL,
  },
  // H13: JSON reporter ALWAYS emitted alongside the human-readable one.
  // - Interactive: list + json + html (operator watches stream; AI parses json)
  // - CI:          dot  + json        (CI dashboard scrapes dot; tooling reads json)
  reporter: isCi
    ? [['dot'], ['json', { outputFile: 'playwright-results.json' }]]
    : [
        ['list'],
        ['json', { outputFile: 'playwright-results.json' }],
        ['html', { open: 'never' }],
      ],
});
