#!/usr/bin/env python3
"""roam-compose-brief.py (v1.1)

Compose per-surface × per-lens INSTRUCTION-*.md files with full env+creds+cwd
context inlined so the executor (subprocess OR another CLI via paste-prompt)
has everything it needs without external lookups.

v1.1 (2026-05-01): added --env / --target-url / --creds-json / --model /
--cwd-convention args. Filename now `INSTRUCTION-<surface>-<lens>.md` (was
`<surface>-<lens>.md`) so manual-mode paste prompts can reference them by a
distinct prefix. Login pre-flight section now inlined verbatim with real
URL + email + password from creds-json (was a TODO comment).

Spec: ROAM-RFC-v1.md section 3, Phase 1 + 2026-05-01 dogfood feedback.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path


HARD_RULES = """## ⛔ HARD RULES (enforced — break = output rejected)

1. You DO NOT judge whether anything is a bug. Just log facts.
2. You DO NOT skip any RCRURD step, even if previous step seemed to fail.
3. You DO NOT stop early on errors. Log the error, continue to next step.
4. You DO NOT classify severity. The commander reads your log later.
5. You DO NOT add commentary. Output is JSONL only, one event per line.
6. If you observe a sub-view (modal, drilldown, child route) you didn't expect,
   emit `spawn-child` event with URL/handle, then continue parent RCRURD.
7. If a Playwright MCP call fails (timeout, server error), log the failure as
   an event and continue. Do NOT retry.
8. Capture full network payloads (request body + response body) verbatim.
   Do NOT redact, summarize, or truncate. PII redaction happens commander-side.
9. If a step's preconditions are not met, log a `precondition-missing` event
   and SKIP only that step's mutation; continue with the rest of RCRURD.
"""


def select_lenses_for_surface(crud: str, entity: str, manual_csv: str | None) -> list[str]:
    """Auto-select lenses based on CRUD ops + entity type. Manual CSV override."""
    if manual_csv and manual_csv != "auto":
        return [s.strip() for s in manual_csv.split(",") if s.strip()]

    lenses = []
    if any(op in crud for op in "CUD"):
        lenses.append("lens-form-lifecycle")
        lenses.append("lens-business-coherence")
    if "R" in crud:
        lenses.append("lens-table-interaction")
    return lenses or ["lens-business-coherence"]


def parse_surfaces_md(path: Path) -> list[dict]:
    """Parse the SURFACES.md table generated by roam-discover-surfaces.py.

    Tolerates entity="?" (the discover script's fallback for unknown entity).
    """
    surfaces = []
    if not path.exists():
        return surfaces
    text = path.read_text(encoding="utf-8")
    row_re = re.compile(r"^\|\s*(S\d+)\s*\|\s*`([^`]+)`\s*\|\s*(\w+)\s*\|\s*(\S+)\s*\|\s*(\w*)\s*\|\s*(.*?)\s*\|")
    for line in text.split("\n"):
        m = row_re.match(line)
        if m:
            surfaces.append({
                "id": m.group(1),
                "url": m.group(2),
                "role": m.group(3),
                "entity": m.group(4),
                "crud": m.group(5),
                "sub_views": m.group(6),
            })
    return surfaces


def find_role_creds(creds: dict, surface_role: str) -> dict | None:
    """Pick credential entry matching surface role; fallback to first role.

    surface.role values seen: admin, merchant, vendor, user (from
    roam-discover heuristic). Match against creds.roles[*].role exact, then
    by prefix (e.g. surface=admin → admin OR superadmin), then fallback.
    """
    roles = (creds or {}).get("roles", [])
    if not roles:
        return None
    # Exact
    for r in roles:
        if r.get("role") == surface_role:
            return r
    # Prefix match
    for r in roles:
        rname = r.get("role", "")
        if rname.startswith(surface_role) or surface_role.startswith(rname.split("-")[0]):
            return r
    return roles[0]


def render_login_preflight(env: str, target_url: str, role_creds: dict, surface_role: str) -> str:
    if not role_creds:
        return f"""## Pre-flight — login (env: {env})

⚠ No credentials available for role `{surface_role}` on env `{env}`.
   Executor must read `.claude/vg.config.md` `credentials.{env}` and pick a
   matching role. If env=prod, login is read-only — do NOT submit forms.
"""
    role = role_creds.get("role", surface_role)
    domain = role_creds.get("domain", "")
    email = role_creds.get("email", "")
    password = role_creds.get("password", "")
    proto = "http" if any(s in domain for s in ("localhost", "127.")) else "https"
    login_url = f"{proto}://{domain}/login"
    return f"""## Pre-flight — login FIRST (env: {env})

You MUST login BEFORE running the protocol below. Do NOT navigate to the
target surface URL until login completes — unauthenticated requests will
return 404/401 and every protocol step will report `precondition_missing`,
yielding a useless run.

### Login steps (verbatim, role = `{role}`):

1. `browser_navigate` → `{login_url}`
2. `browser_snapshot` to confirm login form is visible
3. `browser_fill_form` (or `browser_type` per field) with:
   - email/username: `{email}`
   - password: `{password}`
4. Submit (click login button or press Enter)
5. `browser_wait_for` (e.g. waitForURL away from /login, or for dashboard nav)
6. `browser_snapshot` to confirm authenticated state (sidebar visible, user
   menu shows `{email}`, etc.)

### Login confirmation event (emit BEFORE protocol step 1):

```
{{"surface": "<surface_id>", "step": "login", "ui_after": {{"url": "<post-login-url>", "authenticated": true}}, "network": [...], "timestamp": "<ISO>"}}
```

If login fails (wrong creds, server error, MFA required), emit:
```
{{"surface": "<surface_id>", "step": "login", "ui_after": {{"authenticated": false}}, "error": "<reason>", "timestamp": "<ISO>"}}
```
Then STOP — do not proceed with protocol; no point exercising surface as
unauthenticated.
"""


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--phase-dir", required=True)
    ap.add_argument("--surfaces", required=True, help="Path to SURFACES.md")
    ap.add_argument("--lenses", default="auto", help="csv list or 'auto'")
    ap.add_argument("--output-dir", required=True, help="Per-model dir, e.g. <phase>/roam/codex/")
    ap.add_argument("--env", default="local", help="env name (local|sandbox|staging|prod)")
    ap.add_argument("--target-url", default="", help="Resolved target URL prefix from env, e.g. http://localhost:3001")
    ap.add_argument("--creds-json", default="", help="Path to .env-creds.json with roles+credentials for this env")
    ap.add_argument("--model", default="codex", help="Model name for cwd convention + filename suffix")
    ap.add_argument("--cwd-convention", default="", help="Executor cwd, e.g. ${PHASE_DIR}/roam/codex (used in JSONL output path)")
    ap.add_argument("--include-security", default="false")
    args = ap.parse_args()

    phase_dir = Path(args.phase_dir)
    out_dir = Path(args.output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    surfaces = parse_surfaces_md(Path(args.surfaces))
    if not surfaces:
        print("[roam-compose] no surfaces found — run /vg:roam step 1 first", file=sys.stderr)
        return 2

    creds = {}
    if args.creds_json:
        cp = Path(args.creds_json)
        if cp.exists():
            try:
                creds = json.loads(cp.read_text(encoding="utf-8"))
            except Exception as e:
                print(f"[roam-compose] WARN: bad creds-json: {e}", file=sys.stderr)

    lens_dir = Path(".claude/commands/vg/_shared/lens-prompts")

    cwd_label = args.cwd_convention or f"${{PHASE_DIR}}/roam/{args.model}"

    brief_count = 0
    for surface in surfaces:
        lenses = select_lenses_for_surface(surface["crud"], surface["entity"], args.lenses)

        if args.include_security != "true":
            lenses = [l for l in lenses if not any(s in l for s in ("csrf", "idor", "bfla", "ssrf", "auth-jwt", "input-injection", "open-redirect", "path-traversal", "tenant-boundary", "info-disclosure", "file-upload"))]

        role_creds = find_role_creds(creds, surface["role"])
        login_section = render_login_preflight(args.env, args.target_url, role_creds, surface["role"])

        # Build absolute target URL for the surface
        if args.target_url:
            base = args.target_url.rstrip("/")
            url_path = surface["url"] if surface["url"].startswith("/") else "/" + surface["url"]
            absolute_url = base + url_path
        else:
            absolute_url = surface["url"]

        for lens in lenses:
            lens_md = lens_dir / f"{lens}.md"
            if not lens_md.exists():
                print(f"[roam-compose] WARN: lens {lens} not found, skipping", file=sys.stderr)
                continue

            lens_text = lens_md.read_text(encoding="utf-8")
            if lens_text.startswith("---\n"):
                lens_text = lens_text.split("\n---\n", 1)[1] if "\n---\n" in lens_text else lens_text

            brief_id = f"{surface['id']}-{lens}"
            brief_path = out_dir / f"INSTRUCTION-{brief_id}.md"
            jsonl_filename = f"observe-{brief_id}.jsonl"

            content = f"""# ROAM EXECUTOR INSTRUCTION — {brief_id}

## Target

- **Surface ID:** {surface['id']}
- **Surface URL (absolute):** `{absolute_url}`
- **Auth role:** `{surface['role']}`
- **Entity:** {surface['entity']}
- **CRUD ops observed:** {surface['crud'] or 'R'}
- **Lens:** {lens}
- **Env:** `{args.env}`
- **Model (cwd):** `{args.model}`

## Working directory + output target

- **CWD:** `{cwd_label}` (executor MUST run from this directory)
- **Output JSONL:** `{jsonl_filename}` (relative to cwd, NOT phase dir)
- One JSON object per line, no markdown, no commentary outside JSON.
- Schema per ROAM-RFC-v1.md appendix B. Required keys per event:
  `surface`, `step`, `ui_before` / `ui_after`, `network`, `console_errors`, `timestamp`.

{login_section}

## Lens-specific protocol

{lens_text.strip()}

---

## Prod-env safety (when env=prod)

If env is `prod`, this is a **READ-ONLY** run. SKIP every protocol step that
mutates state (form submit, delete confirm, bulk-action confirm, sort/filter
that triggers writes). Continue read-only steps (snapshot, network capture).
Emit `{{"surface":"...","step":"<name>","skipped":true,"reason":"prod-read-only"}}`
for skipped mutation steps.

For env={args.env}, mutations are allowed per the lens protocol unless the
lens itself flags otherwise.

---

{HARD_RULES}

---

## Done signal

After completing ALL protocol steps, emit ONE final event:

```
{{"surface": "{surface['id']}", "step": "complete", "total_events": <int>, "lens": "{lens}", "timestamp": "<ISO>"}}
```

Then exit. Commander aggregates and analyzes.
"""
            brief_path.write_text(content, encoding="utf-8")
            brief_count += 1

    print(f"[roam-compose] wrote {brief_count} INSTRUCTION-*.md to {out_dir}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
