# shellcheck shell=bash
# inject-rule-cards.sh — emit compressed rule cards for a (skill, step) tuple
#
# zsh compat (2026-05-01, dogfood-driven): when this lib is sourced from
# Claude Code's Bash tool the shell is /bin/zsh, not /bin/bash. zsh leaves
# unquoted `$VAR` unsplit by default, so canonical bash patterns like
# `for a in $REQUIRED; do ...` (where REQUIRED is a whitespace-separated
# string) silently iterate ONCE with `$a` set to the entire string.
# 45+ skill bash blocks rely on the bash word-splitting semantics. Enable
# SH_WORD_SPLIT for the duration of the sourcing shell so they keep
# working under zsh. No-op under bash (setopt is a zsh builtin; the
# `2>/dev/null` swallows the "command not found" error).
[ -n "${ZSH_VERSION:-}" ] && setopt SH_WORD_SPLIT 2>/dev/null

# Harness v2.6 (2026-04-25): Tầng 2 of memory-vs-enforce strategy.
# Cards generated by extract-rule-cards.py from skill files. This helper
# emits the relevant section at step start so AI sees a focused 5-30 line
# digest instead of skimming 1500-3000 line skill body.
#
# Why bash function (not pure Python):
#   Skill file `<step>` bodies invoke bash blocks. Adding a bash function
#   call is the lowest-friction way to wire cards into existing skill
#   structure. Function emits to stdout (so AI sees output in context)
#   and stderr (so logs capture it).
#
# Usage from skill:
#   <step name="0_parse_args">
#     `bash` block:
#       source .claude/commands/vg/_shared/lib/inject-rule-cards.sh
#       inject_rule_cards "vg-build" "0_parse_args"
#     ... rest of step ...
#   </step>
#
# CLI usage (operator manual review):
#   bash .claude/commands/vg/_shared/lib/inject-rule-cards.sh vg-build 0_parse_args
#   bash .claude/commands/vg/_shared/lib/inject-rule-cards.sh vg-build 0_parse_args normal --current-phase 7.14.3
#
# v2.6 Phase D — phase-scoped filter:
#   --current-phase X.Y filters rules whose `phase_pattern` regex doesn't match.
#   Default `phase_pattern: ".*"` for grandfather (all 783+ existing rules pass).
#   New rules going forward can narrow scope (e.g. `^7\.` for phase 7.x only).
#
# Output shape:
#   ━━━ Rules for vg-build / 0_parse_args ━━━
#   [Top-level rules — apply to ALL steps]
#   - R1 [enforce] → validator-X: rule body...
#   ...
#   [Step-specific rules]
#   - [enforce] MUST: text  → validator-Y
#   - [remind] PHẢI: text
#   ...
#   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

REPO_ROOT="${REPO_ROOT:-$(git rev-parse --show-toplevel 2>/dev/null || pwd)}"

# Print rule cards for one step.
# $1 = skill name (e.g., "vg-build")
# $2 = step name (e.g., "0_parse_args")
# $3 = optional mode: "quiet" suppresses output banner
# $4..N = optional flags:
#   --current-phase X.Y   filter rules where phase_pattern regex doesn't match
inject_rule_cards() {
  local skill="$1"
  local step="$2"
  local mode="${3:-normal}"
  shift 3 2>/dev/null || true

  # Parse remaining flags
  local current_phase=""
  while [ "$#" -gt 0 ]; do
    case "$1" in
      --current-phase)
        current_phase="$2"
        shift 2
        ;;
      --current-phase=*)
        current_phase="${1#--current-phase=}"
        shift
        ;;
      *)
        shift
        ;;
    esac
  done

  local cards_file="${REPO_ROOT}/.codex/skills/${skill}/RULES-CARDS.md"
  if [ ! -f "$cards_file" ]; then
    # Cards not generated yet — skill operator should run extract-rule-cards.py
    [ "$mode" = "quiet" ] || echo "▸ rule-cards not found for ${skill} (run: python3 .claude/scripts/validators/extract-rule-cards.py)" >&2
    return 0
  fi

  if [ "$mode" != "quiet" ]; then
    echo ""
    echo "━━━ Rules for ${skill} / ${step} ━━━"
  fi

  # Use awk to extract:
  #   1. Top-level rules section (between "## Top-level rules" and next "##")
  #   2. The step-specific section (between "### Step: \`<step>\`" and next "### Step:")
  #
  # v2.6 Phase D — phase_pattern filter:
  #   Rules may have an inline `phase_pattern: "regex"` marker on their body line
  #   (or a continuation line `  phase_pattern: "regex"`). When --current-phase
  #   is supplied, awk buffers each rule + its body lines, checks phase_pattern
  #   against current_phase, and skips the rule if regex doesn't match.
  #   Default `.*` if marker missing (grandfather all 783+ existing rules).
  #
  # Concatenate both with separator. Skip if section empty.
  awk -v step="### Step: \`${step}\`" -v current_phase="${current_phase}" '
    BEGIN {
      in_top=0; in_step=0
      buf_count=0
      buf_pattern=".*"
      buf_active=0
    }

    # Helper — flush buffered rule (apply phase_pattern filter if current_phase set)
    function flush_buf(    i, ok) {
      if (buf_count == 0) return
      ok = 1
      if (current_phase != "" && buf_pattern != ".*") {
        # Use awk regex (POSIX ERE). Most rule patterns like ^7\. or ^(7|8)\.
        # work as POSIX ERE. Escape sequence \. is honored.
        if (current_phase !~ buf_pattern) ok = 0
      }
      if (ok) {
        for (i = 0; i < buf_count; i++) print buf[i]
      }
      buf_count = 0
      buf_pattern = ".*"
      buf_active = 0
    }

    function buf_add(line) {
      buf[buf_count++] = line
    }

    # Detect phase_pattern marker on any line (inline or continuation)
    function maybe_capture_pattern(line,    m) {
      # Match phase_pattern: "regex" or phase_pattern: regex (no quotes)
      if (match(line, /phase_pattern:[[:space:]]*"[^"]*"/)) {
        m = substr(line, RSTART, RLENGTH)
        sub(/^phase_pattern:[[:space:]]*"/, "", m)
        sub(/"$/, "", m)
        buf_pattern = m
        return 1
      }
      if (match(line, /phase_pattern:[[:space:]]*[^[:space:]]+/)) {
        m = substr(line, RSTART, RLENGTH)
        sub(/^phase_pattern:[[:space:]]*/, "", m)
        buf_pattern = m
        return 1
      }
      return 0
    }

    /^## Top-level rules/ {
      flush_buf()
      in_top=1
      print "[Top-level rules — apply to ALL steps]"
      next
    }

    /^## Per-step rules/ {
      flush_buf()
      in_top=0
      next
    }

    in_top && /^### / { flush_buf(); in_top=0 }
    in_top && /^---$/ { flush_buf(); in_top=0 }

    # Detect start of target step section
    $0 == step {
      flush_buf()
      in_step=1
      print ""
      print "[Step-specific rules: " step "]"
      next
    }

    in_step && /^### Step:/ { flush_buf(); in_step=0 }
    in_step && /^---$/ { flush_buf(); in_step=0 }
    in_step && /^## / { flush_buf(); in_step=0 }

    # Inside top or step section: buffer rule + body lines
    (in_top || in_step) && (NF > 0) {
      # New bullet rule starts → flush previous, begin new buffer
      if ($0 ~ /^- /) {
        flush_buf()
        buf_active=1
        buf_add($0)
        maybe_capture_pattern($0)
        next
      }
      # Continuation line (indented) — append to current buffer
      if (buf_active && $0 ~ /^[[:space:]]+/) {
        buf_add($0)
        maybe_capture_pattern($0)
        next
      }
      # Other content (e.g. **Anti-patterns:** header) — flush + emit raw
      flush_buf()
      print
      next
    }

    # End of file — flush any remaining buffered rule
    END { flush_buf() }
  ' "$cards_file"

  # v2.6.4 (2026-04-26): also emit manual-curated rules from
  # RULES-CARDS-MANUAL.md if present. These persist across regeneration
  # of the auto file. Operator manages via edit-rule-cards.py CLI.
  local manual_file="${REPO_ROOT}/.codex/skills/${skill}/RULES-CARDS-MANUAL.md"
  if [ -f "$manual_file" ]; then
    # Only emit if file has actual rules (not just template placeholders)
    if grep -qE "^\s*-\s+\*\*(MANUAL|OVERRIDE|ANTI)-[0-9]+" "$manual_file" 2>/dev/null; then
      echo ""
      echo "[Manual rules — operator-curated, persisted across regen]"
      # Track section context + entry context — emit rule + body line
      # below it (1 indented continuation line per rule). Captures body
      # text without dragging in unrelated content from the section.
      awk -v step_h="### Step: \`${step}\`" -v step_anti_h="### Step: \`${step}\` — Anti-patterns" -v current_phase="${current_phase}" '
        BEGIN {
          in_top=0; in_step=0; in_over=0; in_entry=0; printed_section=""
          buf_count=0; buf_pattern=".*"; pending_section=""
        }
        function maybe_emit_section_header(name) {
          if (printed_section != name) {
            print "  [" name "]"
            printed_section = name
          }
        }
        # v2.6 Phase D — flush buffered manual rule with phase_pattern filter
        function flush_buf(    i, ok) {
          if (buf_count == 0) return
          ok = 1
          if (current_phase != "" && buf_pattern != ".*") {
            if (current_phase !~ buf_pattern) ok = 0
          }
          if (ok) {
            if (pending_section != "") maybe_emit_section_header(pending_section)
            for (i = 0; i < buf_count; i++) print buf[i]
          }
          buf_count = 0
          buf_pattern = ".*"
          pending_section = ""
        }
        function maybe_capture_pattern(line,    m) {
          if (match(line, /phase_pattern:[[:space:]]*"[^"]*"/)) {
            m = substr(line, RSTART, RLENGTH)
            sub(/^phase_pattern:[[:space:]]*"/, "", m)
            sub(/"$/, "", m)
            buf_pattern = m
            return 1
          }
          if (match(line, /phase_pattern:[[:space:]]*[^[:space:]]+/)) {
            m = substr(line, RSTART, RLENGTH)
            sub(/^phase_pattern:[[:space:]]*/, "", m)
            buf_pattern = m
            return 1
          }
          return 0
        }
        # Detect section transitions (any header line ends current entry context)
        /^#{2,}/ {
          flush_buf()
          in_top = ($0 ~ /^## Top-level/)
          in_step = ($0 == step_h || $0 == step_anti_h)
          in_over = ($0 ~ /^## Overrides/)
          in_entry = 0
          next
        }
        # Inside a relevant section, emit rule entries + 1 body line below
        (in_top || in_step || in_over) && /^- \*\*(MANUAL|OVERRIDE|ANTI)-[0-9]+/ {
          flush_buf()
          if (in_top) pending_section = "Top-level"
          else if (in_step && $0 ~ /ANTI-/) pending_section = step_anti_h
          else if (in_step) pending_section = step_h
          else if (in_over) pending_section = "Overrides"
          buf[buf_count++] = "    " $0
          maybe_capture_pattern($0)
          in_entry = 1
          next
        }
        # Continuation line directly below an entry (body text, indented)
        in_entry && /^\s{2,}/ {
          buf[buf_count++] = "    " $0
          maybe_capture_pattern($0)
          next
        }
        # Blank or new entry boundary
        /^$/ || /^- / { flush_buf(); in_entry = 0 }
        END { flush_buf() }
      ' "$manual_file"
    fi
  fi

  if [ "$mode" != "quiet" ]; then
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
  fi
}

# Convenience: print just the step section (no top-level rules).
inject_rule_cards_step_only() {
  local skill="$1"
  local step="$2"
  local cards_file="${REPO_ROOT}/.codex/skills/${skill}/RULES-CARDS.md"
  [ -f "$cards_file" ] || return 0

  awk -v step="### Step: \`${step}\`" '
    $0 == step { in_step=1; print; next }
    in_step && /^### Step:/ { exit }
    in_step && /^---$/ { exit }
    in_step && /^## / { exit }
    in_step { print }
  ' "$cards_file"
}

# CLI entry point — when invoked directly (not sourced)
if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
  if [ "$#" -lt 2 ]; then
    echo "Usage: $0 <skill> <step> [normal|quiet] [--current-phase X.Y]" >&2
    echo "Example: $0 vg-build 0_parse_args" >&2
    echo "         $0 vg-build 0_parse_args normal --current-phase 7.14.3" >&2
    exit 1
  fi
  inject_rule_cards "$@"
fi
