#!/usr/bin/env python3
"""
Validator: verify-uat-narrative-fields.py — Phase 15 D-05/D-06/D-07

Asserts every prompt block in UAT-NARRATIVE.md has the 4 required fields
(entry, navigation, precondition, expected) — or 6 fields for design-ref
variant prompts (+region, +screenshot_compare).

Detected by presence of the corresponding narration-strings.yaml UAT keys
rendered in the prompt body. UAT-NARRATIVE.md is generated by /vg:accept
step 4b_build_uat_narrative (T5.1, Phase 15 D-10) using flat-key interpolation
({{uat_entry_label}}, {{uat_navigation_label}}, ...).

Logic:
  1. Find UAT-NARRATIVE.md for phase. Missing → BLOCK (step 4b should have run).
  2. Split into prompt blocks (separator: H2 heading or blank-line + ---).
  3. Per prompt block:
       - Identify variant: "design-ref" if block contains region+screenshot
         markers, else "standard".
       - Standard requires: entry, navigation, precondition, expected (4)
       - Design-ref requires: entry, navigation, precondition, expected,
         region, screenshot_compare (6)
       - Missing any → BLOCK.

Usage:  verify-uat-narrative-fields.py --phase 7.14.3
Output: vg.validator-output JSON on stdout
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from _common import Evidence, Output, timer, emit_and_exit, find_phase_dir  # noqa: E402

# Matches rendered Vietnamese OR English label per narration-strings.yaml UAT keys.
# Pattern: "Truy cập|Open" + ":" or similar — case-insensitive.
LABEL_PATTERNS = {
    "entry":              re.compile(r"^(Truy cập|Open)\s*:", re.IGNORECASE | re.MULTILINE),
    "navigation":         re.compile(r"^(Điều hướng|Navigation)\s*:", re.IGNORECASE | re.MULTILINE),
    "precondition":       re.compile(r"^(Tiền điều kiện dữ liệu|Data precondition)\s*:",
                                    re.IGNORECASE | re.MULTILINE),
    "expected":           re.compile(r"^(Hành vi mong đợi|Expected behavior)\s*:",
                                    re.IGNORECASE | re.MULTILINE),
    "region":             re.compile(r"^(Vùng tập trung|Focus region)\s*:",
                                    re.IGNORECASE | re.MULTILINE),
    "screenshot_compare": re.compile(r"^(So sánh với screenshot|Compare against screenshot)\s*:",
                                    re.IGNORECASE | re.MULTILINE),
}

# Block separator: H2 heading (e.g. "## D-04: ...") or "---" line
BLOCK_SPLIT_RE = re.compile(r"\n(?=##\s)|\n---+\n", re.MULTILINE)
# Identifier pattern for D-XX / G-XX / design-ref slug headers
PROMPT_ID_RE = re.compile(r"##\s+([DG]-\d+|design-ref:\s*\S+)", re.IGNORECASE)


def _is_design_ref_block(block: str) -> bool:
    return bool(re.search(r"design-ref:|screenshot|focus region|vùng tập trung",
                          block, re.IGNORECASE))


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--phase", required=True)
    args = ap.parse_args()

    out = Output(validator="uat-narrative-fields")
    with timer(out):
        phase_dir = find_phase_dir(args.phase)
        if not phase_dir:
            out.add(Evidence(type="missing_file",
                             message=f"Phase dir not found for {args.phase}"))
            emit_and_exit(out)

        narrative_path = phase_dir / "UAT-NARRATIVE.md"
        if not narrative_path.exists():
            out.add(Evidence(
                type="missing_file",
                message="UAT-NARRATIVE.md not found",
                file=str(narrative_path),
                fix_hint=(
                    "Run /vg:accept step 4b_build_uat_narrative (auto-fires per D-10) "
                    "to generate UAT-NARRATIVE.md before this validator."
                ),
            ))
            emit_and_exit(out)

        text = narrative_path.read_text(encoding="utf-8", errors="ignore")
        if not text.strip():
            out.add(Evidence(type="empty_file", message="UAT-NARRATIVE.md is empty",
                             file=str(narrative_path)))
            emit_and_exit(out)

        blocks = [b for b in BLOCK_SPLIT_RE.split(text) if b.strip()]
        if not blocks:
            out.add(Evidence(
                type="malformed_content",
                message="No prompt blocks detected in UAT-NARRATIVE.md",
                file=str(narrative_path),
                fix_hint="Each prompt block must start with '## D-XX' or '## G-XX' header.",
            ))
            emit_and_exit(out)

        total = 0
        for block in blocks:
            id_match = PROMPT_ID_RE.search(block)
            if not id_match:
                continue  # skip non-prompt sections (intro, footer)
            total += 1
            prompt_id = id_match.group(1)
            is_design_ref = _is_design_ref_block(block)
            required = ["entry", "navigation", "precondition", "expected"]
            if is_design_ref:
                required += ["region", "screenshot_compare"]

            missing = [f for f in required if not LABEL_PATTERNS[f].search(block)]
            if missing:
                out.add(Evidence(
                    type="schema_violation",
                    message=(f"Prompt {prompt_id} missing field(s): "
                             f"{', '.join(missing)}"),
                    file=str(narrative_path),
                    expected=required,
                    actual=[f for f in required if f not in missing],
                    fix_hint=(
                        "Re-run /vg:accept step 4b. If template is correct, check "
                        "narration-strings.yaml has all uat_* keys for the active locale."
                    ),
                ))

        if not out.evidence:
            out.evidence.append(Evidence(
                type="info",
                message=f"All {total} UAT prompt block(s) have required fields",
            ))

    emit_and_exit(out)


if __name__ == "__main__":
    main()
